export const START_LOADING_PETS = 'START_LOADING_PETS';
export const SUCCESSFULLY_LOADED_PETS = 'SUCCESSFULLY_LOADED_PETS';

export const START_LOADING_OWNERS = 'START_LOADING_OWNERS';
export const SUCCESSFULLY_LOADED_OWNERS = 'SUCCESSFULLY_LOADED_OWNERS';


// not implemented yet
export const ADD_PET = 'ADD_PET';
export const FAILED_LOADING_PETS = 'FAILED_LOADING_PETS';

export const ADD_OWNER= 'ADD_OWNER';
export const FAILED_LOADING_OWNERS = 'FAILED_LOADING_OWNERS';
