//login actions hopefully
export const AUTHENTICATED = 'AUTHENTICATED';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';

//pet actions
export const START_LOADING_PETS = 'START_LOADING_PETS';
export const SUCCESSFULLY_LOADED_PETS = 'SUCCESSFULLY_LOADED_PETS';

export const SUCCESSFULLY_CREATED_PET = 'SUCCESSFULLY_CREATED_PET';
export const ERROR_CREATING_PET = 'ERROR_CREATING_PET';

//owner actions
export const START_LOADING_OWNERS = 'START_LOADING_OWNERS';
export const SUCCESSFULLY_LOADED_OWNERS = 'SUCCESSFULLY_LOADED_OWNERS';

export const SUCCESSFULLY_CREATED_OWNER = 'SUCCESSFULLY_CREATED_OWNER';
export const SUCCESSFULLY_REMOVED_OWNER = 'SUCCESSFULLY_REMOVED_OWNER';


//actions occuring on /pets/:pet_id
export const START_LOADING_PET_FEEDINGS = 'START_LOADING_PET_FEEDINGS';
export const SUCCESSFULLY_LOADED_PET_FEEDINGS = 'SUCCESSFULLY_LOADED_PET_FEEDINGS';

//feedings actions
export const SUCCESSFULLY_CREATED_FEEDING = 'SUCCESSFULLY_CREATED_FEEDING';


// not implemented yet
export const ADD_PET = 'ADD_PET';
export const FAILED_LOADING_PETS = 'FAILED_LOADING_PETS';

export const ADD_OWNER= 'ADD_OWNER';
export const FAILED_LOADING_OWNERS = 'FAILED_LOADING_OWNERS';
